import type { Metadata } from "next";
<<<<<<< HEAD
import "./globals.css";



export const metadata: Metadata = {
  title: "Steve_Rasoafanirindraibe",
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
>>>>>>> b5063a7a396de0b3f896a0364576c283c172e6b0
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en" >
      <body
=======
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
>>>>>>> b5063a7a396de0b3f896a0364576c283c172e6b0
      >
        {children}
      </body>
    </html>
  );
}
